apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinestore-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinestore
  template:
    metadata:
      labels:
        app: onlinestore
    spec:
      containers:
        - name: onlinestore
          image: onlinestore