apiVersion: v1
kind: Service
metadata:
    name: onlinestorenp-srv
spec:
    type: NodePort
    selector: 
      app: onlinestore
    ports:
      - name: onlinestore
        protocol: TCP
        port: 80
        targetPort: 80 